<h1 align="center">Hi ðŸ‘‹, I'm Majall</h1>
<h3 align="center">MERN Stack Developer â€¢ AI Learner</h3>

<p align="left"> <img src="https://komarev.com/ghpvc/?username=majall&label=Profile%20views&color=0e75b6&style=flat" alt="majall" /> </p>

- ðŸ”­ Iâ€™m currently working on **Real Time Chat App**

- ðŸ“« How to reach me **majaalmj7@gmail.com**

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://instagram.com/_majall" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/instagram.svg" alt="_majall" height="30" width="40" /></a>
<a href="https://discord.gg/majall_27984" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/discord.svg" alt="majall_27984" height="30" width="40" /></a>
</p>

<h3 align="left">Languages and Tools:</h3>
<h3 align="left">Languages & Tools</h3>

<h4>Frontend</h4>
<p align="left">
  <a href="https://reactjs.org/" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg" width="40"/>
  </a>
  <a href="https://angular.io" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/angularjs/angularjs-original.svg" width="40"/>
  </a>
  <a href="https://tailwindcss.com/" target="_blank">
    <img src="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg" width="40"/>
  </a>
  <a href="https://getbootstrap.com" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain.svg" width="40"/>
  </a>
  <a href="https://www.w3.org/html/" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg" width="40"/>
  </a>
  <a href="https://www.w3schools.com/css/" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg" width="40"/>
  </a>
</p>

<h4>Backend</h4>
<p align="left">
  <a href="https://nodejs.org" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg" width="40"/>
  </a>
  <a href="https://nestjs.com/" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nestjs/nestjs-plain.svg" width="40"/>
  </a>
  <a href="https://spring.io/" target="_blank">
    <img src="https://www.vectorlogo.zone/logos/springio/springio-icon.svg" width="40"/>
  </a>
  <a href="https://www.php.net" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg" width="40"/>
  </a>
</p>

<h4>Databases</h4>
<p align="left">
  <a href="https://www.mongodb.com/" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg" width="40"/>
  </a>
  <a href="https://www.mysql.com/" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg" width="40"/>
  </a>
  <a href="https://www.postgresql.org" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg" width="40"/>
  </a>
</p>

<h4>Languages</h4>
<p align="left">
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" width="40"/>
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg" width="40"/>
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg" width="40"/>
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" width="40"/>
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original.svg" width="40"/>
</p>

<h4>Tools & Cloud</h4>
<p align="left">
  <a href="https://git-scm.com/" target="_blank">
    <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" width="40"/>
  </a>
  <a href="https://postman.com" target="_blank">
    <img src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg" width="40"/>
  </a>
  <a href="https://aws.amazon.com" target="_blank">
    <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg" width="40"/>
  </a>
  <a href="https://www.selenium.dev" target="_blank">
    <img src="https://raw.githubusercontent.com/detain/svg-logos/master/svg/selenium-logo.svg" width="40"/>
  </a>
</p>


<p>&nbsp;<img align="center" src="https://github-readme-stats.vercel.app/api?username=majall&show_icons=true&locale=en" alt="majall" /></p>

<p><img align="center" src="https://github-readme-streak-stats.herokuapp.com/?user=majall&" alt="majall" /></p>



